# Generated by Django 5.0.4 on 2024-04-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_swtich_teclado_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teclado',
            name='conectividad',
            field=models.TextField(blank=True, max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='formato',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='keycaps',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='teclado',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
